# frozen_string_literal: true

default_platform(:ios)

platform :ios do

  def authenticate_api
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_KEY_CONTENT"],
      is_key_content_base64: true
    )
  end

  desc "Prepare keychain and certificate"
  lane :setup_ci_keychain do
    cert_path = File.expand_path("../ci_certificate.p12", Dir.pwd)
    keychain_name = "ci_keychain"
    keychain_password = SecureRandom.hex

    delete_keychain(name: keychain_name) if File.exist?(File.expand_path("~/Library/Keychains/#{keychain_name}-db"))

    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    import_certificate(
      certificate_path: cert_path,
      certificate_password: ENV["IOS_CERTIFICATE_PASSWORD"],
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )
  end

  desc "Increment build number based on appstore"
  lane :sync_build_number do
    authenticate_api
    new_build = latest_testflight_build_number(initial_build_number: 1) + 1

    increment_build_number(
      build_number: new_build,
      xcodeproj: "iosApp.xcodeproj"
    )
  end

  desc "Build the app"
  lane :build_ipa do
    setup_ci_keychain
    sync_build_number

    profile_path = File.expand_path("../ci_profile.mobileprovision", Dir.pwd)
    install_provisioning_profile(path: profile_path)

    profile_uuid = sh("grep UUID -A1 -a #{profile_path.shellescape} | grep -io \"[-A-Z0-9]\\{36\\}\"").strip

    build_app(
      scheme: "iosApp",
      project: "iosApp.xcodeproj",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "VPlanPlus.ipa",
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=BYCH2H5X5G",
      export_options: {
        method: "app-store",
        teamID: "BYCH2H5X5G",
        provisioningProfiles: { "plus.vplan.app.VPlanPlus" => profile_uuid }
      }
    )
    delete_keychain(name: "ci_keychain")
  end

  # --- Channel Lanes ---

  desc "Release for internal testers"
  lane :internal do
    build_ipa
    authenticate_api
    upload_to_testflight(groups: ["Internal"])
  end

  desc "Closed testing"
  lane :closed do
    build_ipa
    authenticate_api
    upload_to_testflight(groups: ["Closed"])
  end

  desc "Open testing"
  lane :open do
    build_ipa
    authenticate_api
    upload_to_testflight(groups: ["Open"])
  end

  desc "Production"
  lane :production do
    build_ipa
    authenticate_api
    upload_to_testflight(
      skip_submission: true,
      distribute_external: false
    )
  end

  error do |lane, exception|
    delete_keychain(name: "ci_keychain") if File.exist?(File.expand_path("~/Library/Keychains/ci_keychain-db"))
  end
end